spring:
  datasource:
    url: jdbc:h2:file:./data/mediadb-dev
    username: spring-dev
    password: hddvd4life
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.settings.trace: false
    console.settings.web-allow-others: false
server:
  error:
    include-message: always